---
kind: pipeline
type: docker
name: backend-dev-ci-cd

trigger:
  branch:
    - dev
  event:
    - push

steps:
  # 1. Test
  - name: test
    image: golang:1.24
    commands:
      - go mod tidy

  # 2. Build & push Docker image
  - name: docker-build-publish
    image: plugins/docker
    settings:
      repo: kiminodare/backend-api-hovarlay
      tags:
        - dev
        - ${DRONE_COMMIT_SHA}
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD

  # 3. Deploy to dev server
  - name: deploy-to-dev
    image: alpine:latest
    commands:
      - apk add --no-cache openssh-client bash
      - eval $(ssh-agent -s)
      - echo "$SSH_KEY_PASSPHRASE" | ssh-add <(echo "$SSH_KEY")
      - ssh -o StrictHostKeyChecking=no ubuntu@43.134.40.159 "
        echo \"$BACKEND_ENV_HOVARLAY\" | tr -d '\r' > /tmp/backend.env &&
        docker pull kiminodare/backend-api-hovarlay:dev &&
        docker stop backend || true &&
        docker rm backend || true &&
        docker run -d --name backend --restart always -p 9888:9888 --env-file /tmp/backend.env kiminodare/backend-api-hovarlay:dev &&
        docker logs --tail 50 backend &&
        docker image prune -f &&
        rm /tmp/backend.env
        "
    environment:
      BACKEND_ENV_HOVARLAY:
        from_secret: BACKEND_ENV_HOVARLAY
      SSH_KEY:
        from_secret: SSH_KEY
      SSH_KEY_PASSPHRASE:
        from_secret: SSH_KEY_PASSPHRASE
